###########################################################################
path_classifiers:
  test:
    - test
extraction:
  cpp:
    prepare:
      packages:
        - libpoppler-qt5-dev
        - zlib1g-dev
        - libssl-dev
        - libffi-dev
        - pybind11-dev
        - libgl-dev
        - python3-dev
        - qtbase5-dev-tools
        - qtbase5-dev
        - qt5-default
        - qtchooser
        - qt5-qmake
        - libqt5svg5-dev
        - qttools5-dev
        - qttranslations5-l10n
        - cmake
        - gcc
        - build-essential
    configure:
      command:
        - git clone https://gitlab.com/inkscape/lib2geom.git
        - pushd lib2geom
        - git checkout 37876ed4
        - cmake -B build -GNinja -DCMAKE_INSTALL_PREFIX=build/install -D2GEOM_TESTING=OFF
        - cmake --build build --target install
        - popd
        - mkdir build
        - cd build
        - cmake -DGENERATE_ICONS=off -DCMAKE_BUILD_TYPE=Release -DQT_QM_PATH="/usr/share/qt5/translations/" -DCMAKE_INSTALL_PREFIX="/usr;../lib2geom/build/install/lib/cmake" ..
    index:
      build_command:
        - cd build
        - make
  python:
    after_prepare:
      - export PATH=$LGTM_WORKSPACE/tools:$PATH

