###########################################################################
path_classifiers:
  test:
    - test
extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - g++-10
        - gcc-10
        - libffi-dev
        - libgl-dev
        - libpoppler-qt5-dev
        - libqt5svg5-dev
        - libssl-dev
        - pybind11-dev
        - python3-dev
        - qt5-default
        - qt5-qmake
        - qtchooser
        - qtbase5-dev
        - qtbase5-dev-tools
        - qttools5-dev
        - software-properties-common
        - zlib1g-dev
    configure:
      command:
        - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - > /usr/share/keyrings/kitware-archive-keyring.gpg \
        - echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' > /etc/apt/sources.list.d/kitware.list \
        - apt-get update && apt-get install -y cmake
        - git clone https://gitlab.com/inkscape/lib2geom.git
        - cd lib2geom; git checkout 37876ed4; cd ..
        - cmake
            -S lib2geom
            -DCMAKE_CXX_COMPILER=g++-10
            -DCMAKE_C_COMPILER=gcc-10
            -B build-lib2geom
            -GNinja
            -DCMAKE_INSTALL_PREFIX=$LGTM_WORKSPACE/install
            -D2GEOM_TESTING=OFF
        - cmake --build build-lib2geom --target install
        - git clone https://github.com/fmtlib/fmt.git
        - cd fmt; git checkout 8.0.1; cd ..
        - cmake
            -S fmt
            -B build-fmt
            -GNinja
            -DCMAKE_CXX_COMPILER=g++-10
            -DCMAKE_C_COMPILER=gcc-10
            -DCMAKE_INSTALL_PREFIX=$LGTM_WORKSPACE/install
        - cmake --build build-fmt --target install
        - cmake
            -S .
            -B build
            -DBUILD_TRANSLATION=OFF
            -DUSE_QT_5_12=ON
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_CXX_COMPILER=g++-10
            -DCMAKE_C_COMPILER=gcc-10
            -DCMAKE_INSTALL_PREFIX=$LGTM_WORKSPACE/install
            -DCMAKE_PREFIX_PATH=$LGTM_WORKSPACE/install
    index:
      build_command:
        - cd build
        - make
  python:
    after_prepare:
      - export PATH=$LGTM_WORKSPACE/tools:$PATH
