name: 'Install Common Packages'
description: 'Install commonly required packages'
inputs:
  additional_packages:
    description: additional packages to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      run: sudo apt-get update && sudo apt-get install -y
           build-essential
           libboost-all-dev
           libcairo2-dev
           libdouble-conversion-dev
           libffi-dev
           libgl-dev
           libgsl-dev
           libssl-dev
           imagemagick
           ninja-build
           python3-dev
           python3-numpy
           zlib1g-dev
           ${{inputs.additional_packages}}
