name: 'Prepare MSYS2'
description: 'Prepare MSYS2 environment'
runs:
  using: composite
  steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-cython
          mingw-w64-x86_64-dlfcn
          mingw-w64-x86_64-double-conversion
          mingw-w64-x86_64-fmt
          mingw-w64-x86_64-gsl
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-gtkmm3
          mingw-w64-x86_64-icu
          mingw-w64-x86_64-imagemagick
          mingw-w64-x86_64-kitemmodels-qt5
          mingw-w64-x86_64-libffi
          mingw-w64-x86_64-libdeflate
          mingw-w64-x86_64-libwebp
          mingw-w64-x86_64-mesa
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-nsis
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-poppler-qt6
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-numpy
          mingw-w64-x86_64-python-pytest
          mingw-w64-x86_64-qt6
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-zlib
