name: 'install from git'
description: 'Install from git'
inputs:
  url:
    description: The url to the repository
    required: true
  name:
    description: The name of the dependency. This name will be used in the build and source path.
    required: true
  checkout:
    description: The checkout to build
    required: true
  configure_flags:
    description: Additional flags passed to the configure command
    required: false
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git clone "${{inputs.url}}" "${{inputs.name}}"
        pushd "${{inputs.name}}"; git checkout "${{inputs.checkout}}"; popd
    - shell: msys2 {0}
      run: |
        cmake -S "${{inputs.name}}" \
              -B "${{inputs.name}}-build" \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=dependencies \
              ${{inputs.configure_flags}}
        cmake --build "${{inputs.name}}-build" \
              --target install \
              --config Release \
              -j4
