#  There is already a `cmake` (3.20) installed miraculously
#  and `dpkg -S cmake` does not find a corresponding package.
#  We must not install the `libkf5itemmodels-dev` package because
#  it depends on the bionic Qt5-packages (5.9) which will hide
#  the beineri-Qt5-packages (5.15).

name: 'Prepare Focal'
description: 'Install required packages'
runs:
  using: composite
  steps:
    - shell: bash
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - shell: bash
      run: sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic
    - shell: bash
      run: sudo apt-get update && sudo apt-get install -y
           build-essential
           g++-9
           gcc-9
           libboost-all-dev
           libcairo2-dev
           libdouble-conversion-dev
           libffi-dev
           libgl-dev
           libgsl-dev
           libopenjp2-7-dev
           libssl-dev
           imagemagick
           ninja-build
           python3-dev
           qt515base
           qt515svg
           qt515tools
           qt515translations
           qt515x11extras
           zlib1g-dev
    - shell: bash
      run: sudo update-alternatives
            --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
            --slave /usr/bin/g++ g++ /usr/bin/g++-9
