name: 'Prepare Focal'
description: 'Install required packages'
runs:
  using: composite
  steps:
    - shell: bash
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - shell: bash
      run: sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic
    - shell: bash
      run: sudo apt-get update && sudo apt-get install -y
           build-essential
           cmake
           g++-9
           gcc-9
           libboost-all-dev
           libcairo2-dev
           libdouble-conversion-dev
           libffi-dev
           libgl-dev
           libgsl-dev
           libkf5itemmodels-dev
           libpoppler-qt5-dev
           libqt5svg5-dev
           libssl-dev
           imagemagick
           ninja-build
           python3-dev
           qt515base
           qt515svg
           qt515tools
           qt515translations
           qt515x11extras
           zlib1g-dev
