name: focal, clang, static tests, unit tests
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-focal
    steps:
      - uses: actions/checkout@v2
      - run: cmake -S .
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DBUILD_TESTING=ON
                   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
                   -DCMAKE_CXX_COMPILER=clang++
                   -DCMAKE_C_COMPILER=clang
      - uses: actions/upload-artifact@v2
        with:
          name: configure
          path: build
  build:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-focal
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - uses: actions/download-artifact@v2
        with:
          name: configure
          path: build
      - run: ls
      - run: ls build
      - run: cmake --build build
                   --config Release
                   -j4
      - run: tar -cvf build.tar build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar
  clazy:
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-focal
    needs: configure
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: configure
          path: build
      - run: |
          files="$(build-scripts/files.py --mode changed)"
          if [ -z "$files" ]; then
            echo "Skip clazy: No relevant files have changed."
          else
            clazy --standalone -p build --ignore-included-files $files
          fi
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-focal
    needs: configure
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: configure
          path: build
      - run: |
          files="$(build-scripts/files.py --mode changed)"
          if [ -z "$files" ]; then
            echo "Skip clang-tidy: No relevant files have changed."
          else
            clang-tidy -p build $(build-scripts/files.py --mode changed) $files
          fi
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-focal
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: tar -xf build.tar
      - run: ctest --test-dir build --output-on-failure
