name: focal, gcc, unit tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-focal
    steps:
      - uses: actions/checkout@v2
      - run: cmake -S .
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DBUILD_TESTING=ON
      - run: cmake --build build
                   --config Release
                   -j4
      - run: ctest --test-dir build --output-on-failure
