name: Create AppImage on Bionic
on: [push]
jobs:
  Create-AppImage-Bionic:
    runs-on: ubuntu-latest
    container:
      image: pasbi/ommpfritt-bionic
      options: --cap-add SYS_ADMIN --device /dev/fuse --privileged
    steps:
      - uses: actions/checkout@v2
        with:
          path: omm
          fetch-depth: 0
      - run: cmake -S omm
                   -B omm-build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DCMAKE_PREFIX_PATH="${QT_PREFIX}"
                   -DBUILD_TESTING=OFF
                   -DCMAKE_INSTALL_PREFIX=install
      - run: cmake --build omm-build --target install --config Release -j4
      - run: cmake --build omm-build --target icons --config Release -j4
      - run: cmake -S omm -B omm-build
      - run: cmake --build omm-build --target install --config Release -j4
      - run: cmake --build omm-build --target appimage --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: Ommpfritt-AppImage
          path: omm-build/ommpfritt*.AppImage
  Make-Release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: Create-AppImage-Bionic
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Ommpfritt-AppImage
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ommpfritt-*.AppImage"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
  Verify-Focal:
    runs-on: ubuntu-18.04
    needs: Create-AppImage-Bionic
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Ommpfritt-AppImage
      - run: ls /usr/lib/x86_64-linux-gnu/
      - run: ls /usr/lib/x86_64-linux-gnu/libOpenGL.so.0
      - run: chmod +x ommpfritt-*.AppImage
      - run: LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ ./ommpfritt-*.AppImage -platform offscreen --no-opengl --version
      - run: ./ommpfritt-*.AppImage -platform offscreen --no-opengl --version
      - run: ./ommpfritt-*.AppImage -platform offscreen --no-opengl --version | grep ommpfritt
  Verify-Bionic:
    runs-on: ubuntu-20.04
    needs: Create-AppImage-Bionic
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Ommpfritt-AppImage
      - run: ls /usr/lib/x86_64-linux-gnu/
      - run: ls /usr/lib/x86_64-linux-gnu/libOpenGL.so.0
      - run: chmod +x ommpfritt-*.AppImage
      - run: LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ ./ommpfritt-*.AppImage -platform offscreen --no-opengl --version
      - run: ./ommpfritt-*.AppImage -platform offscreen --no-opengl --version
      - run: ./ommpfritt-*.AppImage -platform offscreen --no-opengl --version | grep ommpfritt
