name: GitHub Actions Demo
on: [push]
jobs:
  Build-Focal-Travis:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y
             g++
             libboost-all-dev
             libcairo2-dev
             libdouble-conversion-dev
             libffi-dev
             libgl-dev
             libgsl-dev
             libkf5itemmodels-dev
             libpoppler-qt5-dev
             libqt5svg5-dev
             libssl-dev
             imagemagick
             ninja-build
             python3-dev
             qt5-default
             zlib1g-dev
      - name: Checkout lib2geom
        run: |
          git clone https://gitlab.com/inkscape/lib2geom.git
          cd lib2geom
          git checkout 37876ed4
          cd ..
      - name: configure lib2geom
        run: cmake -S lib2geom
                   -B build-lib2geom
                   -GNinja
                   -D2GEOM_TESTING=OFF
                   -DCMAKE_INSTALL_PREFIX=install
      - name: build lib2geom
        run: cmake --build build-lib2geom --target install
      - name: configure omm
        run: cmake -S ${{ github.workspace }}
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DQT_QM_PATH=/usr/share/qt5/translations/
                   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: build omm
        run: cmake --build build --target package
