name: Build on Windows 2019
on: [push]
jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-msys
      - run: ls /mingw64/bin/libssl-1_1-x64.dll /mingw64/bin/libcrypto-1_1-x64.dll
      - run: git clone https://gitlab.com/inkscape/lib2geom.git
      - run: cd lib2geom; git checkout 37876ed4; cd ..
      - run: cmake -S lib2geom
                   -B lib2geom-build
                   -DCMAKE_BUILD_TYPE=Release
                   -DCMAKE_INSTALL_PREFIX=dependencies
                   -G"MSYS Makefiles"
                   -D2GEOM_TESTING=OFF
      - run: cmake --build lib2geom-build --target install --config Release -j4
      - run: cmake -P cmake/patch_getprerequisites_module.cmake
      - run: cmake -S .
                   -B build
                   -G"MSYS Makefiles"
                   -DCMAKE_BUILD_TYPE=Release
                   -DCMAKE_PREFIX_PATH=dependencies
                   -DCMAKE_INSTALL_PREFIX=omm-install
                   -DPython3_ROOT_DIR=/mingw64/bin
      - run: cmake --build build --target all --config Release -j4
      - run: cmake --build build --target install --config Release -j4
      - run: python build/generate-icons.py
      - run: cmake -S .  -B build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build
            dependencies
  package:
    needs: build
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-msys
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: cmake --build build --target package --config Release -j4
      - uses: actions/upload-artifact@v2
        with:
          name: ommpfritt-installer-win2019
          path: build/ommpfritt-*-win64.exe
  unit-test:
    needs: build
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-msys
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: ctest --test-dir build --output-on-failure
  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ommpfritt-installer-win2019
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ommpfritt-*.exe"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
  verify-package:
    needs: package
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ommpfritt-installer-win2019
      - run: ./ommpfritt-*-win64.exe /S /D=$(pwd)\install | Out-Null
      - name: Test if application runs
        run: if (-Not (&"$(pwd)\install\bin\ommpfritt-cli.exe" --version | Select-String ommpfritt)) { exit 1 }
  verify-package-expect-fail:
    needs: package
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ommpfritt-installer-win2019
      - run: ./ommpfritt-*-win64.exe /S /D=$(pwd)\install | Out-Null
      - name: Test if application runs
        run: if (-Not (&"$(pwd)\install\bin\ommpfritt-cli.exe" --version | Select-String xommpfritt)) { exit 1 }
