name: GitHub Actions Demo
on: [push]
jobs:
  Build-lib2geom-Focal:
    runs-on: ubuntu-20.04
    steps:
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y
           build-essential
           cmake
           g++
           libboost-all-dev
           libdouble-conversion-dev
           ninja-build
      - name: Checkout lib2geom
        run: |
          git clone https://gitlab.com/inkscape/lib2geom.git
          cd lib2geom
          git checkout 37876ed4
          cd ..
      - name: configure lib2geom
        run: cmake -S lib2geom
                   -B build-lib2geom
                   -GNinja
                   -D2GEOM_TESTING=OFF
                   -DCMAKE_INSTALL_PREFIX=lib2geom-install
      - name: build lib2geom
        run: sudo cmake --build build-lib2geom --target install
      - name: Upload lib2geom focal
        uses: actions/upload-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
  Build-libommpfritt-Focal-gcc:
    runs-on: ubuntu-20.04
    needs: Build-lib2geom-Focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        uses: ./.github/actions/prepare-focal
      - name: Download lib2geom installation
        uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - name: configure ommpfritt
        run: cmake -S ${{ github.workspace }}
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DQT_QM_PATH=/usr/share/qt5/translations/
                   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
                   -DCMAKE_PREFIX_PATH=lib2geom-install
      - name: Build libommpfritt
        run: cmake --build build --target libommpfritt
      - name: Upload libommpfritt build (Focal)
        uses: actions/upload-artifact@v2
        with:
          name: libommpfritt-focal-gcc
          path: build
  Build-libommpfritt-Focal-clang:
    runs-on: ubuntu-20.04
    needs: Build-lib2geom-Focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        uses: ./.github/actions/prepare-focal
      - name: Download lib2geom installation
        uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - name: configure ommpfritt
        run: cmake -S ${{ github.workspace }}
                   -B build
                   -GNinja
                   -DCMAKE_BUILD_TYPE=Release
                   -DQT_QM_PATH=/usr/share/qt5/translations/
                   -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
                   -DCMAKE_PREFIX_PATH=lib2geom-install
                   -DCMAKE_CXX_COMPILER=clang
                   -DCMAKE_C_COMPILER=clang
      - name: Build libommpfritt
        run: cmake --build build --target libommpfritt
      - name: Upload libommpfritt build (Focal)
        uses: actions/upload-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: build
  Build-ommpfritt-Focal-gcc:
    runs-on: ubuntu-20.04
    needs: Build-libommpfritt-Focal-gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        uses: ./.github/actions/prepare-focal
      - name: Download lib2geom installation
        uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - name: Download libommpfritt build
        uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-gcc
          path: build
      - name: Build ommpfritt
        run: cmake --build build --target ommpfritt
      - name: Upload ommpfritt build (Focal)
        uses: actions/upload-artifact@v2
        with:
          name: ommpfritt-focal-gcc
          path: build
  Clazy-Check:
    runs-on: ubuntu-20.04
    needs: Build-libommpfritt-Focal-clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        uses: ./.github/actions/prepare-focal
      - name: install clazy
        run: sudo apt-get update && sudo apt-get install clazy
      - name: Download libommpfritt build
        uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-clang
          path: build
      - name: Download lib2geom installation
        uses: actions/download-artifact@v2
        with:
          name: lib2geom-focal
          path: lib2geom-install
      - name: Perform clazy checks
        run: clazy --standalone -p build --ignore-included-files $(build-scripts/files.py --mode changed)
  Unit-Test-libommpfritt:
    runs-on: ubuntu-20.04
    needs: Build-libommpfritt-Focal-gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        uses: ./.github/actions/prepare-focal
      - name: Download libommpfritt build
        uses: actions/download-artifact@v2
        with:
          name: libommpfritt-focal-gcc
          path: build
      - name: Unit Tests
        run: |
          ctest --version
          cd build
          ls
          ctest
